### ISSUE TITLE
Задание 1 

### ISSUE THREAD

**Issue by djadjka** [BossOfTheGym/Project#1]
1)Не знаю, мб ты его еще не доделал и знаешь это, но скажу что задание выполнено не до конца.
2)Молодец что юзаешь Sublime, но мы, если что, не сможем тебе с ним помочь с ним =)

**Comment by BossOfTheGym** [comment]
Чего не хватает?

**Comment by djadjka** [comment]
Внимательно читай условие

**Comment by djadjka** [comment]
Задание зачтено, но 
1)Все равно невнимательно прочел задание, status.txt нужно было дополнить 
2)месседжи в коммитах должны быть осмысленными,а не 'оооооооооооо'
